services:
  marche-conclu-eureka-server: "ghcr.io/igdevx/eureka-server:v0.1.0"
  marche-conclu-config-server: "ghcr.io/igdevx/config-server:v0.3.0"
  marche-conclu-main-gateway-api: "ghcr.io/igdevx/marche-conclu-main-gateway-api:v1.0.0"
