services:
  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile.dev
    profiles: [all, discovery, shared]
    ports:
      - "8761:8761"
    networks:
      - dev-network

  config-server:
    build:
      context: ./config-server
      dockerfile: Dockerfile.dev
    profiles: [all, config, shared]
    ports:
      - "8888:8888"
    depends_on:
      eureka-server:
        condition: service_started
        restart: true
    networks:
      - dev-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:18
    profiles: [all, db, shared]
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - dev-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    profiles: [all, minio, shared, shop]
    ports:
      - "9000:9000"      # API
      - "9001:9001"      # Console Web
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - dev-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.6
    profiles: [all, elasticsearch, shared, shop]
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - dev-network

  kafka:
    image: apache/kafka
    profiles: [all, kafka, shared]
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - dev-network

  keycloak:
    build:
      context: ./keycloak
      dockerfile: Dockerfile.dev
    command: start-dev --http-port=3000 --import-realm
    profiles: [all, keycloak, shared]
    environment:
      KC_DB_URL: jdbc:postgresql://db:5432/keycloak
      KC_DB_USERNAME: user
      KC_DB_PASSWORD: pwd
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HOSTNAME: keycloak
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_started
        restart: true
    networks:
      - dev-network

  main-gateway-api:
    build:
      context: ./main-gateway-api
      dockerfile: Dockerfile.dev
    profiles: [all, gateway, shared]
    ports:
      - "8080:8080"
    depends_on:
      config-server:
        condition: service_started
        restart: true
      keycloak:
        condition: service_started
        restart: true
    networks:
      - dev-network

  account-service:
    build:
      context: ./services/account-service
      dockerfile: Dockerfile.dev
    profiles: [all, account]
    ports:
      - "5001:5001"
    depends_on:
      main-gateway-api:
        condition: service_started
        restart: true
      db:
        condition: service_started
        restart: true
    networks:
      - dev-network

  shop-service:
    build:
      context: ./services/shop-service
      dockerfile: Dockerfile.dev
    profiles: [all, shop]
    ports:
      - "5002:5002"
    depends_on:
      main-gateway-api:
        condition: service_started
        restart: true
      db:
        condition: service_healthy
        restart: true
      config-server:
        condition: service_healthy
    networks:
      - dev-network

  image-service:
    build:
      context: ./services/nano/image-service
      dockerfile: Dockerfile.dev
    profiles: [all, image]
    ports:
      - "5004:5004"
    depends_on:
      main-gateway-api:
        condition: service_started
        restart: true
      minio:
        condition: service_healthy
        restart: true
      config-server:
        condition: service_healthy
    networks:
      - dev-network

  notification-service:
    build:
      context: ./services/notification-service
      dockerfile: Dockerfile.dev
    profiles: [all, notification]
    ports:
      - "5005:5000"
    depends_on:
      main-gateway-api:
        condition: service_started
        restart: true
      config-server:
        condition: service_healthy
    networks:
      - dev-network

  payment-service:
    build:
      context: ./services/payment-service
      dockerfile: Dockerfile.dev
    profiles: [all, payment]
    ports:
      - "5006:5000"
    depends_on:
      main-gateway-api:
        condition: service_started
        restart: true
      config-server:
        condition: service_healthy
    networks:
      - dev-network

  order-service:
    build:
      context: ./services/order-service
      dockerfile: Dockerfile.dev
    profiles: [all, order]
    ports:
      - "5007:5000"
    depends_on:
      main-gateway-api:
        condition: service_started
        restart: true
      config-server:
        condition: service_healthy
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge

volumes:
  db-data:
  minio-data:
  es-data:
